CREATE TABLE user_details (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    full_name VARCHAR2(100),
    bio VARCHAR2(1000),
    avatar_url VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--drop table User_details;
--=====================================================================================================================

CREATE TABLE Experience (
    experience_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR2(100) NOT NULL,
    company VARCHAR2(100) NOT NULL,
    location VARCHAR2(100),
    start_date DATE NOT NULL,
    end_date DATE,
    description VARCHAR2(1000),
    currently_working VARCHAR2(5) CHECK( currently_working IN ('true', 'false', 'TRUE', 'FALSE')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);

--=====================================================================================================================

CREATE TABLE Education (
    education_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    institution VARCHAR2(100) NOT NULL,
    degree VARCHAR2(100) NOT NULL,
    field_of_study VARCHAR2(100),
    start_date DATE NOT NULL,
    end_date DATE,
    description VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);

--=====================================================================================================================

CREATE TABLE Project (
    project_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(1000),
    start_date DATE,
    end_date DATE,
    url VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);

--=====================================================================================================================

CREATE TABLE Skill (
    skill_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR2(100) NOT NULL,
    proficiency VARCHAR2(15) CHECK(proficiency IN ('beginner', 'intermediate', 'advanced') )NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);


--=====================================================================================================================

CREATE TABLE Certification (
    certification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR2(100) NOT NULL,
    authority VARCHAR2(100),
    license_number VARCHAR2(50),
    start_date DATE,
    end_date DATE,
    url VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);


--=====================================================================================================================

CREATE TABLE Publication (
    publication_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR2(200) NOT NULL,
    authors VARCHAR2(200),
    journal VARCHAR2(100),
    publication_date DATE,
    url VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);

--=====================================================================================================================

CREATE TABLE Reference (
    reference_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR2(100) NOT NULL,
    position VARCHAR2(100),
    company VARCHAR2(100),
    contact_info VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);

--=====================================================================================================================

CREATE TABLE Contact (
    contact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    type VARCHAR2(50) NOT NULL,
    value VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);

--=====================================================================================================================

CREATE TABLE SocialMedia (
    social_media_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    platform VARCHAR2(50) NOT NULL,
    url VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id)
);

--=====================================================================================================================





